#order服务生产环境使用的配置文件使用order-dev.yml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud?characterEncoding=UTF-8@&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  cloud:
    stream:
      bindings:
        input:
          destination: productMessageQueue
          #在input这里这是一个组，即将所有的消息消费者都放到一个组里，这样只要是同一个消息队列的消息，
          #多个消费者集群的系统里，只有要一个消费者实例会收到消息
          group: productMessageGroup
        output:
          destination: productMessageQueue
          #指定在rabbitMQ管理主页上显示的文本内容
          contentType: application/json
  redis:
    host: 132.232.48.14
    port: 6379
    password: redispassword!@#
