#order服务所有环境都使用的配置就放到order.yml这个配置文件里
logging:
  file: /usr/local/tomcat/ORDER.log
  pattern:
    level: info
    file: "[ORDER] [%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] %-5level = > %msg%n"
  level:
    com:
      shyfay:
        order:
          repository: debug
spring:
  redis:
    #本地
    host: 172.0.0.1
    #部署到rancher上之后
    #host: 192.168.5.113
    port: 6379
    password: redispassword!@#
